--FACULTIES
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (100, 'Psychology', 50, 150);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (200, 'Programming', 10, 90);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (300, 'Child development', 60, 90);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (400, 'Applied mathematics', 30, 70);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (500, 'Biology', 35, 85);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (600, 'Biochemistry', 20, 30);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (700, 'Modern Medicine', 7, 33);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (800, 'Architectural design', 65, 135);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (900, 'Physical education', 50, 100);
INSERT INTO Faculties (id, name, budget_places, total_places) VALUES (1000, 'Neurobiology', 25, 55);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Psychology', 50, 150);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Programming', 10, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Child development', 60, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Applied mathematics', 30, 70);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Biology', 35, 85);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Biochemistry', 20, 30);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Modern Medicine', 7, 33);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Architectural design', 65, 135);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Physical education', 50, 100);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Neurobiology', 25, 55);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Psychology', 50, 150);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Programming', 10, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Child development', 60, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Applied mathematics', 30, 70);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Biology', 35, 85);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Biochemistry', 20, 30);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Modern Medicine', 7, 33);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Architectural design', 65, 135);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Physical education', 50, 100);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Neurobiology', 25, 55);
--USERS
INSERT INTO Users (id, username, email, password) VALUES (100, 'one', 'nr_one@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (200, 'two', 'nr_two@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (300, 'three', 'nr_three@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (400, 'four', 'nr_four@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (500, 'five', 'nr_five@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (600, 'six', 'nr_six@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (700, 'seven', 'nr_seven@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (800, 'eight', 'nr_eight@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (900, 'nine', 'nr_nine@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1000, 'ten', 'nr_ten@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password, role) VALUES (1100, 'admin', 'admin@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg', 'ADMIN');
INSERT INTO Users (id, username, email, password) VALUES (110, 'eleven', 'eleven@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1100, '1100', '1100@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1200, '1200', '1200@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1300, '1300', '1300@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1400, '1400', '1400@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1500, '1500', '1500@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1600, '1600', '1600@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1700, '1700', '1700@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1800, '1800', '1800@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1900, '1900', '1900@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1110, '1110', '1110@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1210, '1210', '1210@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');INSERT INTO Users (id, username, email, password) VALUES (100, 'one', 'nr_one@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1220, '1220', '1220@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1310, '1310', '1310@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1410, '1410', '1410@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1510, '1510', '1510@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1610, '1610', '1610@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1710, '1710', '1710@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1810, '1810', '1810@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1910, '1910', '1910@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1111, '1111', '1111@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');
INSERT INTO Users (id, username, email, password) VALUES (1121, '1121', '1121@test.com', '$argon2id$v=19$m=4096,t=3,p=1$LKuNxYF+oFtsqnzIQZ6DHw$nuybRVf4FXV77hO4AlAygnhEg4v/b4NenV0fWF7kPHg');

--APPLICANTS
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID, certificate) VALUES (11, 'Adam', 'Smith', 'Gdansk', 'Pomorskie', 'UG', 100, 'LDk8hYMV');
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (12, 'Pola', 'Jones', 'Warsaw', 'Mazowiecki', 'UW', 200);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (13, 'Joe', 'Poe', 'Gdansk', 'Pomorskie', 'PG', 300);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (14, 'Donna', 'Noble', 'London', 'UK', 'UG', 400);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (15, 'Rose', 'Tyler', 'Gdansk', 'Pomorskie', 'UG', 500);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (16, 'Rory', 'Williams', 'Warsaw', 'Mazowieckie', 'PW', 600);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (17, 'John', 'Moriarty', 'Krakow', 'Małopolskie', 'UAM', 700);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (18, 'Iga', 'Swiatek', 'Warsaw', 'Mazowieckie', 'PG', 800);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (19, 'Feliks', 'Goodboy', 'Gdansk', 'Pomorskie', 'PG', 900);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (20, 'Doctor', 'Tenth', 'Gallifrey', 'Universe', 'UG', 1000);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID, certificate) VALUES (11, 'Adam', 'Smith', 'Gdansk', 'Pomorskie', 'UG', 100, 'LDk8hYMV');
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (12, 'Pola', 'Jones', 'Warsaw', 'Mazowiecki', 'UW', 200);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (13, 'Joe', 'Poe', 'Gdansk', 'Pomorskie', 'PG', 300);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (14, 'Donna', 'Noble', 'London', 'UK', 'UG', 400);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (15, 'Rose', 'Tyler', 'Gdansk', 'Pomorskie', 'UG', 500);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (16, 'Rory', 'Williams', 'Warsaw', 'Mazowieckie', 'PW', 600);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (17, 'John', 'Moriarty', 'Krakow', 'Małopolskie', 'UAM', 700);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (18, 'Iga', 'Swiatek', 'Warsaw', 'Mazowieckie', 'PG', 800);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (19, 'Feliks', 'Goodboy', 'Gdansk', 'Pomorskie', 'PG', 900);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (20, 'Doctor', 'Tenth', 'Gallifrey', 'Universe', 'UG', 1000);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID, certificate) VALUES (11, 'Adam', 'Smith', 'Gdansk', 'Pomorskie', 'UG', 100, 'LDk8hYMV');
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (12, 'Pola', 'Jones', 'Warsaw', 'Mazowiecki', 'UW', 200);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (13, 'Joe', 'Poe', 'Gdansk', 'Pomorskie', 'PG', 300);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (14, 'Donna', 'Noble', 'London', 'UK', 'UG', 400);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (15, 'Rose', 'Tyler', 'Gdansk', 'Pomorskie', 'UG', 500);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (16, 'Rory', 'Williams', 'Warsaw', 'Mazowieckie', 'PW', 600);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (17, 'John', 'Moriarty', 'Krakow', 'Małopolskie', 'UAM', 700);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (18, 'Iga', 'Swiatek', 'Warsaw', 'Mazowieckie', 'PG', 800);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (19, 'Feliks', 'Goodboy', 'Gdansk', 'Pomorskie', 'PG', 900);
INSERT INTO Applicants (id, first_name, last_name, city, region, educational_institution, user_ID) VALUES (20, 'Doctor', 'Tenth', 'Gallifrey', 'Universe', 'UG', 1000);

--SCORES
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (11, 'Maths', 89);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (11, 'English', 67);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (11, 'IT', 90);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (11, 'Polish', 55);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (11, 'Physics', 70);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (12, 'Maths', 99);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (12, 'English', 75);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (12, 'IT', 97);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (12, 'Polish', 84);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (12, 'Physics', 79);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (13, 'Maths', 73);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (13, 'English', 34);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (13, 'IT', 79);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (13, 'Polish', 65);
INSERT INTO Scores (applicant_id, subject_name, result) VALUES (13, 'Physics', 54);
--REQUESTS
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 100, 50);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 200, 60);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 300, 70);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 400, 80);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 500, 90);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 600, 100);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 700, 95);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 800, 85);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 900, 75);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (13, 1000, 65);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (11, 200, 55);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (11, 400, 45);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (11, 600, 88);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (12, 200, 21);
INSERT INTO Enrollment_Requests (applicant_id, faculty_id, points) VALUES (12, 400, 79);

INSERT INTO SUBJECTS (NAME) VALUES ('Polish');
INSERT INTO SUBJECTS (NAME) VALUES ('English');
INSERT INTO SUBJECTS (NAME) VALUES ('Maths');
INSERT INTO SUBJECTS (NAME) VALUES ('IT');
INSERT INTO SUBJECTS (NAME) VALUES ('Physics');

INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (100, 1);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (100, 2);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (200, 3);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (200, 4);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (200, 5);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (300, 1);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (300, 2);
INSERT INTO FACULTIES_SUBJECTS (FACULTY_ID, SUBJECT_ID) VALUES (300, 3);