INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Psychology', 50, 150);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Programming', 10, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Child development', 60, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Applied mathematics', 30, 70);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Biology', 35, 85);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Biochemistry', 20, 30);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Modern Medicine', 7, 33);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Architectural design', 65, 135);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Physical education', 50, 100);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('Neurobiology', 25, 55);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Psychology', 50, 150);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Programming', 10, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Child development', 60, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Applied mathematics', 30, 70);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Biology', 35, 85);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Biochemistry', 20, 30);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Modern Medicine', 7, 33);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Architectural design', 65, 135);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Physical education', 50, 100);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('1Neurobiology', 25, 55);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Psychology', 50, 150);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Programming', 10, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Child development', 60, 90);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Applied mathematics', 30, 70);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Biology', 35, 85);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Biochemistry', 20, 30);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Modern Medicine', 7, 33);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Architectural design', 65, 135);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Physical education', 50, 100);
INSERT INTO Faculties (name, budget_places, total_places) VALUES ('2Neurobiology', 25, 55);